[2025-10-27T16:00:07.399+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-27T16:00:07.419+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_to_postgres_etl.load_to_postgres scheduled__2025-10-27T15:00:00+00:00 [queued]>
[2025-10-27T16:00:07.425+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_to_postgres_etl.load_to_postgres scheduled__2025-10-27T15:00:00+00:00 [queued]>
[2025-10-27T16:00:07.426+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-27T16:00:07.436+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_to_postgres> on 2025-10-27 15:00:00+00:00
[2025-10-27T16:00:07.442+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1028) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-27T16:00:07.444+0000] {standard_task_runner.py:64} INFO - Started process 1030 to run task
[2025-10-27T16:00:07.444+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mysql_to_postgres_etl', 'load_to_postgres', 'scheduled__2025-10-27T15:00:00+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/mysql_to_postgres_etl.py', '--cfg-path', '/tmp/tmpz81kzanr']
[2025-10-27T16:00:07.445+0000] {standard_task_runner.py:91} INFO - Job 84: Subtask load_to_postgres
[2025-10-27T16:00:07.478+0000] {task_command.py:426} INFO - Running <TaskInstance: mysql_to_postgres_etl.load_to_postgres scheduled__2025-10-27T15:00:00+00:00 [running]> on host a0076f556b70
[2025-10-27T16:00:07.540+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_to_postgres_etl' AIRFLOW_CTX_TASK_ID='load_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-10-27T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-27T15:00:00+00:00'
[2025-10-27T16:00:07.541+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-27T16:00:07.582+0000] {base.py:84} INFO - Using connection ID 'postgres_con' for task execution.
[2025-10-27T16:00:07.590+0000] {mysql_to_postgres_etl.py:235} INFO - Successfully loaded 64 rows into PostgreSQL
[2025-10-27T16:00:07.590+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-10-27T16:00:07.590+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-27T16:00:07.601+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=mysql_to_postgres_etl, task_id=load_to_postgres, run_id=scheduled__2025-10-27T15:00:00+00:00, execution_date=20251027T150000, start_date=20251027T160007, end_date=20251027T160007
[2025-10-27T16:00:07.625+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-10-27T16:00:07.641+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-27T16:00:07.643+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
