[2025-10-27T15:43:02.686+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-27T15:43:02.703+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_to_postgres_etl.create_target_table manual__2025-10-27T15:42:59.687694+00:00 [queued]>
[2025-10-27T15:43:02.708+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_to_postgres_etl.create_target_table manual__2025-10-27T15:42:59.687694+00:00 [queued]>
[2025-10-27T15:43:02.709+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-27T15:43:02.719+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): create_target_table> on 2025-10-27 15:42:59.687694+00:00
[2025-10-27T15:43:02.724+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=672) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-27T15:43:02.725+0000] {standard_task_runner.py:64} INFO - Started process 674 to run task
[2025-10-27T15:43:02.726+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mysql_to_postgres_etl', 'create_target_table', 'manual__2025-10-27T15:42:59.687694+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/mysql_to_postgres_etl.py', '--cfg-path', '/tmp/tmpry5wap2a']
[2025-10-27T15:43:02.727+0000] {standard_task_runner.py:91} INFO - Job 64: Subtask create_target_table
[2025-10-27T15:43:02.764+0000] {task_command.py:426} INFO - Running <TaskInstance: mysql_to_postgres_etl.create_target_table manual__2025-10-27T15:42:59.687694+00:00 [running]> on host a0076f556b70
[2025-10-27T15:43:02.837+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_to_postgres_etl' AIRFLOW_CTX_TASK_ID='create_target_table' AIRFLOW_CTX_EXECUTION_DATE='2025-10-27T15:42:59.687694+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-27T15:42:59.687694+00:00'
[2025-10-27T15:43:02.838+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-27T15:43:02.846+0000] {base.py:84} INFO - Using connection ID 'postgres_con' for task execution.
[2025-10-27T15:43:02.849+0000] {sql.py:495} INFO - Running statement: 
    SELECT EXISTS (
        SELECT FROM information_schema.tables 
        WHERE table_schema = 'public' 
        AND table_name = 'shipping_fact'
    );
    , parameters: None
[2025-10-27T15:43:02.852+0000] {sql.py:504} INFO - Rows affected: 1
[2025-10-27T15:43:02.857+0000] {base.py:84} INFO - Using connection ID 'postgres_con' for task execution.
[2025-10-27T15:43:02.860+0000] {sql.py:495} INFO - Running statement: 
        CREATE TABLE shipping_fact (
            id SERIAL PRIMARY KEY,
            receipt_id INTEGER UNIQUE NOT NULL,
            customer_id INTEGER,
            last_status VARCHAR(20),
            pos_origin VARCHAR(100),
            pos_destination VARCHAR(100),
            created_at TIMESTAMP,
            updated_at TIMESTAMP,
            deleted_at TIMESTAMP,
            etl_updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
        
        -- Create index for better query performance
        CREATE INDEX idx_shipping_customer_id ON shipping_fact(customer_id);
        CREATE INDEX idx_shipping_status ON shipping_fact(last_status);
        , parameters: None
[2025-10-27T15:43:02.873+0000] {mysql_to_postgres_etl.py:71} INFO - Target table created successfully!
[2025-10-27T15:43:02.873+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-10-27T15:43:02.873+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-27T15:43:02.882+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=mysql_to_postgres_etl, task_id=create_target_table, run_id=manual__2025-10-27T15:42:59.687694+00:00, execution_date=20251027T154259, start_date=20251027T154302, end_date=20251027T154302
[2025-10-27T15:43:02.905+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-10-27T15:43:02.926+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-27T15:43:02.928+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
