[2025-10-27T15:00:09.978+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-27T15:00:09.997+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_to_postgres_etl.load_to_postgres scheduled__2025-10-27T14:00:00+00:00 [queued]>
[2025-10-27T15:00:10.003+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_to_postgres_etl.load_to_postgres scheduled__2025-10-27T14:00:00+00:00 [queued]>
[2025-10-27T15:00:10.003+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-27T15:00:10.013+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_to_postgres> on 2025-10-27 14:00:00+00:00
[2025-10-27T15:00:10.019+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=467) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-27T15:00:10.020+0000] {standard_task_runner.py:64} INFO - Started process 469 to run task
[2025-10-27T15:00:10.021+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mysql_to_postgres_etl', 'load_to_postgres', 'scheduled__2025-10-27T14:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/mysql_to_postgres_etl.py', '--cfg-path', '/tmp/tmp3a19xx5_']
[2025-10-27T15:00:10.022+0000] {standard_task_runner.py:91} INFO - Job 21: Subtask load_to_postgres
[2025-10-27T15:00:10.062+0000] {task_command.py:426} INFO - Running <TaskInstance: mysql_to_postgres_etl.load_to_postgres scheduled__2025-10-27T14:00:00+00:00 [running]> on host a0076f556b70
[2025-10-27T15:00:10.134+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_to_postgres_etl' AIRFLOW_CTX_TASK_ID='load_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-10-27T14:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-27T14:00:00+00:00'
[2025-10-27T15:00:10.136+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-27T15:00:10.137+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-27T15:00:10.137+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: load_to_postgres() missing 1 required positional argument: 'df'
[2025-10-27T15:00:10.145+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=mysql_to_postgres_etl, task_id=load_to_postgres, run_id=scheduled__2025-10-27T14:00:00+00:00, execution_date=20251027T140000, start_date=20251027T150009, end_date=20251027T150010
[2025-10-27T15:00:10.157+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 21 for task load_to_postgres (load_to_postgres() missing 1 required positional argument: 'df'; 469)
[2025-10-27T15:00:10.200+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-10-27T15:00:10.224+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-27T15:00:10.226+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
