[2025-10-27T15:33:37.985+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-27T15:33:38.001+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_to_postgres_etl.run_data_quality_checks manual__2025-10-27T15:33:29.332998+00:00 [queued]>
[2025-10-27T15:33:38.007+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_to_postgres_etl.run_data_quality_checks manual__2025-10-27T15:33:29.332998+00:00 [queued]>
[2025-10-27T15:33:38.007+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-27T15:33:38.017+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_data_quality_checks> on 2025-10-27 15:33:29.332998+00:00
[2025-10-27T15:33:38.022+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=540) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-27T15:33:38.023+0000] {standard_task_runner.py:64} INFO - Started process 542 to run task
[2025-10-27T15:33:38.024+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mysql_to_postgres_etl', 'run_data_quality_checks', 'manual__2025-10-27T15:33:29.332998+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/mysql_to_postgres_etl.py', '--cfg-path', '/tmp/tmp5odebofh']
[2025-10-27T15:33:38.025+0000] {standard_task_runner.py:91} INFO - Job 62: Subtask run_data_quality_checks
[2025-10-27T15:33:38.059+0000] {task_command.py:426} INFO - Running <TaskInstance: mysql_to_postgres_etl.run_data_quality_checks manual__2025-10-27T15:33:29.332998+00:00 [running]> on host a0076f556b70
[2025-10-27T15:33:38.123+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_to_postgres_etl' AIRFLOW_CTX_TASK_ID='run_data_quality_checks' AIRFLOW_CTX_EXECUTION_DATE='2025-10-27T15:33:29.332998+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-27T15:33:29.332998+00:00'
[2025-10-27T15:33:38.125+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-27T15:33:38.131+0000] {base.py:84} INFO - Using connection ID '***_con' for task execution.
[2025-10-27T15:33:38.139+0000] {sql.py:495} INFO - Running statement: SELECT COUNT(*) FROM transactions, parameters: None
[2025-10-27T15:33:38.149+0000] {sql.py:504} INFO - Rows affected: 1
[2025-10-27T15:33:38.154+0000] {base.py:84} INFO - Using connection ID 'postgres_con' for task execution.
[2025-10-27T15:33:38.157+0000] {sql.py:495} INFO - Running statement: SELECT COUNT(*) FROM shipping_fact, parameters: None
[2025-10-27T15:33:38.158+0000] {sql.py:504} INFO - Rows affected: 1
[2025-10-27T15:33:38.159+0000] {mysql_to_postgres_etl.py:234} WARNING - Record count mismatch: MySQL=100000, PostgreSQL=1000
[2025-10-27T15:33:38.164+0000] {base.py:84} INFO - Using connection ID 'postgres_con' for task execution.
[2025-10-27T15:33:38.166+0000] {sql.py:495} INFO - Running statement: 
        SELECT COUNT(*) 
        FROM shipping_fact 
        WHERE receipt_id IS NULL 
        OR customer_id IS NULL 
        OR last_status IS NULL
    , parameters: None
[2025-10-27T15:33:38.167+0000] {sql.py:504} INFO - Rows affected: 1
[2025-10-27T15:33:38.172+0000] {base.py:84} INFO - Using connection ID 'postgres_con' for task execution.
[2025-10-27T15:33:38.175+0000] {sql.py:495} INFO - Running statement: 
        SELECT COUNT(*) 
        FROM shipping_fact 
        WHERE last_status = 'done' 
        AND deleted_at IS NULL
    , parameters: None
[2025-10-27T15:33:38.177+0000] {sql.py:504} INFO - Rows affected: 1
[2025-10-27T15:33:38.177+0000] {mysql_to_postgres_etl.py:259} INFO - Data quality checks completed!
[2025-10-27T15:33:38.177+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-10-27T15:33:38.178+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-27T15:33:38.187+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=mysql_to_postgres_etl, task_id=run_data_quality_checks, run_id=manual__2025-10-27T15:33:29.332998+00:00, execution_date=20251027T153329, start_date=20251027T153338, end_date=20251027T153338
[2025-10-27T15:33:38.203+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-10-27T15:33:38.215+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-27T15:33:38.217+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
