[2025-10-27T15:48:05.940+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-27T15:48:05.961+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_to_postgres_etl.transform_data manual__2025-10-27T15:47:58.119240+00:00 [queued]>
[2025-10-27T15:48:05.969+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_to_postgres_etl.transform_data manual__2025-10-27T15:47:58.119240+00:00 [queued]>
[2025-10-27T15:48:05.969+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-27T15:48:05.980+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_data> on 2025-10-27 15:47:58.119240+00:00
[2025-10-27T15:48:05.987+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=795) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-27T15:48:05.988+0000] {standard_task_runner.py:64} INFO - Started process 797 to run task
[2025-10-27T15:48:05.988+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mysql_to_postgres_etl', 'transform_data', 'manual__2025-10-27T15:47:58.119240+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/mysql_to_postgres_etl.py', '--cfg-path', '/tmp/tmpooj2la3s']
[2025-10-27T15:48:05.990+0000] {standard_task_runner.py:91} INFO - Job 72: Subtask transform_data
[2025-10-27T15:48:06.025+0000] {task_command.py:426} INFO - Running <TaskInstance: mysql_to_postgres_etl.transform_data manual__2025-10-27T15:47:58.119240+00:00 [running]> on host a0076f556b70
[2025-10-27T15:48:06.104+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_to_postgres_etl' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2025-10-27T15:47:58.119240+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-27T15:47:58.119240+00:00'
[2025-10-27T15:48:06.105+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-27T15:48:06.150+0000] {mysql_to_postgres_etl.py:161} INFO - Transformed data: 64 rows ready for loading
[2025-10-27T15:48:06.167+0000] {python.py:237} INFO - Done. Returned value was:     receipt_id  customer_id  ...           deleted_at             etl_updated_at
0        95344         4341  ...                 None 2025-10-27 15:48:06.149524
1           96         4303  ...  2025-10-27 14:50:06 2025-10-27 15:48:06.149524
2        26196         1028  ...  2025-10-27 14:51:11 2025-10-27 15:48:06.149524
3        59202         3608  ...  2025-10-27 14:51:24 2025-10-27 15:48:06.149524
4        92662         4923  ...                 None 2025-10-27 15:48:06.149524
..         ...          ...  ...                  ...                        ...
59       67953          901  ...                 None 2025-10-27 15:48:06.149524
60       63858         4612  ...                 None 2025-10-27 15:48:06.149524
61       48366         2508  ...                 None 2025-10-27 15:48:06.149524
62       32707         1970  ...  2025-10-27 15:46:41 2025-10-27 15:48:06.149524
63        5092         1556  ...                 None 2025-10-27 15:48:06.149524

[64 rows x 9 columns]
[2025-10-27T15:48:06.188+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-27T15:48:06.209+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=mysql_to_postgres_etl, task_id=transform_data, run_id=manual__2025-10-27T15:47:58.119240+00:00, execution_date=20251027T154758, start_date=20251027T154805, end_date=20251027T154806
[2025-10-27T15:48:06.250+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-10-27T15:48:06.276+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-27T15:48:06.278+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
