[2025-10-27T16:00:05.266+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-27T16:00:05.283+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_to_postgres_etl.transform_data scheduled__2025-10-27T15:00:00+00:00 [queued]>
[2025-10-27T16:00:05.289+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_to_postgres_etl.transform_data scheduled__2025-10-27T15:00:00+00:00 [queued]>
[2025-10-27T16:00:05.289+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-27T16:00:05.298+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_data> on 2025-10-27 15:00:00+00:00
[2025-10-27T16:00:05.303+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1015) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-27T16:00:05.305+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mysql_to_postgres_etl', 'transform_data', 'scheduled__2025-10-27T15:00:00+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/mysql_to_postgres_etl.py', '--cfg-path', '/tmp/tmpgivc4eps']
[2025-10-27T16:00:05.306+0000] {standard_task_runner.py:64} INFO - Started process 1017 to run task
[2025-10-27T16:00:05.306+0000] {standard_task_runner.py:91} INFO - Job 83: Subtask transform_data
[2025-10-27T16:00:05.339+0000] {task_command.py:426} INFO - Running <TaskInstance: mysql_to_postgres_etl.transform_data scheduled__2025-10-27T15:00:00+00:00 [running]> on host a0076f556b70
[2025-10-27T16:00:05.401+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_to_postgres_etl' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2025-10-27T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-27T15:00:00+00:00'
[2025-10-27T16:00:05.402+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-27T16:00:05.438+0000] {mysql_to_postgres_etl.py:167} INFO - Transformed data: 64 rows ready for loading
[2025-10-27T16:00:05.452+0000] {python.py:237} INFO - Done. Returned value was:     receipt_id  customer_id  ...           deleted_at             etl_updated_at
0         1843         1566  ...                 None 2025-10-27 16:00:05.437076
1        43763         2188  ...                 None 2025-10-27 16:00:05.437076
2          479         3230  ...                 None 2025-10-27 16:00:05.437076
3        62126         3280  ...  2025-10-27 14:03:51 2025-10-27 16:00:05.437076
4        58940         4702  ...                 None 2025-10-27 16:00:05.437076
..         ...          ...  ...                  ...                        ...
59       82230         4293  ...                 None 2025-10-27 16:00:05.437076
60       96070         2352  ...                 None 2025-10-27 16:00:05.437076
61       10101         2461  ...  2025-10-27 14:55:48 2025-10-27 16:00:05.437076
62       25642         3437  ...                 None 2025-10-27 16:00:05.437076
63        7046         4560  ...                 None 2025-10-27 16:00:05.437076

[64 rows x 9 columns]
[2025-10-27T16:00:05.472+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-27T16:00:05.491+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=mysql_to_postgres_etl, task_id=transform_data, run_id=scheduled__2025-10-27T15:00:00+00:00, execution_date=20251027T150000, start_date=20251027T160005, end_date=20251027T160005
[2025-10-27T16:00:05.528+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-10-27T16:00:05.550+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-27T16:00:05.552+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
